In [41]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score
)

print("Libraries loaded successfully!")

Libraries loaded successfully!

In [42]:
df = pd.read_csv("opay_transactions.csv")

print("Data loaded successfully!")
print("Number of students:", len(df))

df.head(8)

Data loaded successfully!
Number of students: 500

,amount,time_of_day,device_type,location_match,prev_fraud_flag,is_fraud
0,198805.0,6,2,0,0,0
1,263383.0,22,0,0,0,0
2,67840.0,3,1,1,0,0
3,161908.0,13,1,1,0,0
4,412514.0,10,0,1,0,0
5,221655.0,6,1,1,0,0
6,117720.0,20,3,1,0,0
7,248881.0,12,3,1,0,0

In [43]:
df.tail(8)

,amount,time_of_day,device_type,location_match,prev_fraud_flag,is_fraud
492,343007.0,15,0,0,0,0
493,133926.0,9,0,1,0,0
494,258793.0,7,2,1,1,0
495,282747.0,16,2,1,0,0
496,337372.0,10,1,1,0,0
497,427570.0,18,0,1,0,0
498,91362.0,9,3,1,1,0
499,116510.0,13,3,1,0,0

In [44]:
print("Columns in our dataset:")
print(df.columns.tolist())

print()

print("First 5 transactions:")
print(df.head())

Columns in our dataset:
['amount', 'time_of_day', 'device_type', 'location_match', 'prev_fraud_flag', 'is_fraud']

First 5 transactions:
     amount  time_of_day  device_type  location_match  prev_fraud_flag  \
0  198805.0            6            2               0                0
1  263383.0           22            0               0                0
2   67840.0            3            1               1                0
3  161908.0           13            1               1                0
4  412514.0           10            0               1                0

   is_fraud
0         0
1         0
2         0
3         0
4         0

In [45]:
print("Missing values:")
print(df.isnull().sum())

Missing values:
amount             0
time_of_day        0
device_type        0
location_match     0
prev_fraud_flag    0
is_fraud           0
dtype: int64

In [46]:
print("Number of fraudulent transactions:", (df["is_fraud"] == 1).sum())
print("Number of  non-fraudulent transactions:", (df["is_fraud"] == 0).sum())

Number of fraudulent transactions: 21
Number of  non-fraudulent transactions: 479

In [47]:
X = df[["amount", "time_of_day", "device_type", "location_match", "prev_fraud_flag"]]

y = df["is_fraud"]

print("Our input features (X):")
print(X.head())

print()

print("Our target (y):")
print(y.head())

Our input features (X):
     amount  time_of_day  device_type  location_match  prev_fraud_flag
0  198805.0            6            2               0                0
1  263383.0           22            0               0                0
2   67840.0            3            1               1                0
3  161908.0           13            1               1                0
4  412514.0           10            0               1                0

Our target (y):
0    0
1    0
2    0
3    0
4    0
Name: is_fraud, dtype: int64

In [48]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training transactions:", len(X_train))
print("Testing transactions:", len(X_test))

Training transactions: 400
Testing transactions: 100

In [49]:
model = DecisionTreeClassifier(
    max_depth=8,
    random_state=42
)

model.fit(X_train, y_train)

print("Model training complete!")

Model training complete!

In [50]:
y_pred = model.predict(X_test)

print("Predictions made successfully!")
print("Number of predictions:", len(y_pred))

print()
print("Actual answers:")
print(y_test.values)

print()
print("Model predictions:")
print(y_pred)

Predictions made successfully!
Number of predictions: 100

Actual answers:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]

Model predictions:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

In [51]:
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[94  1]
 [ 4  1]]

In [52]:
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

print("True Negative (TN):", tn)
print("False Positive (FP):", fp)
print("False Negative (FN):", fn)
print("True Positive (TP):", tp)

True Negative (TN): 94
False Positive (FP): 1
False Negative (FN): 4
True Positive (TP): 1

In [53]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", round(accuracy * 100, 1), "%")

Accuracy: 95.0 %

In [54]:
precision = precision_score(y_test, y_pred)

print("Precision:", round(precision * 100, 1), "%")

Precision: 50.0 %

In [55]:
recall = recall_score(y_test, y_pred)

print("Recall:", round(recall * 100, 1), "%")

Recall: 20.0 %

In [56]:
f1 = f1_score(y_test, y_pred)

print("F1-score:", round(f1 * 100, 1), "%")

F1-score: 28.6 %

In [57]:
print("===== MODEL EVALUATION =====")

print("Accuracy :", round(accuracy * 100, 1), "%")
print("Precision:", round(precision * 100, 1), "%")
print("Recall   :", round(recall * 100, 1), "%")
print("F1-score :", round(f1 * 100, 1), "%")

print()
print("Confusion Matrix:")
print(cm)

===== MODEL EVALUATION =====
Accuracy : 95.0 %
Precision: 50.0 %
Recall   : 20.0 %
F1-score : 28.6 %

Confusion Matrix:
[[94  1]
 [ 4  1]]

### Test the Model with a New Transactions

In [58]:
# Enter information about a new transaction
# amount", "time_of_day", "device_type", "location_match", "prev_fraud_flag"

amount = 434765.0
time_of_day = 20
device_type = 3
location_match = 0
prev_fraud_flag = 1


new_transaction = pd.DataFrame({
    "amount": [amount],
    "time_of_day": [time_of_day],
    "device_type": [device_type],
    "location_match": [location_match],
    "prev_fraud_flag": [prev_fraud_flag]
})

print("New Transaction:")
print(new_transaction)

New Transaction:
     amount  time_of_day  device_type  location_match  prev_fraud_flag
0  434765.0           20            3               0                1

In [59]:
prediction = model.predict(new_transaction)[0]

if prediction == 1:
    print("Prediction: PASS")
else:
    print("Prediction: FAIL")

Prediction: FAIL

In [60]:
probability = model.predict_proba(new_transaction)[0]

print("Probability of FAIL:", round(probability[1] * 100, 1), "%")
print("Probability of PASS:", round(probability[0] * 100, 1), "%")

Probability of FAIL: 0.0 %
Probability of PASS: 100.0 %